config/routes.rb
Rails.application.routes.draw do
  root :to => 'home#index'
  devise_for :users
  resources :foods
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user

  validates :name, :presence => true
  validates :calories, :presence => true
  validates :protein, :presence => true
  validates :carbs, :presence => true
  validates :fat, :presence => true

  def self.food_history(user)
    @foods = Food.where(user_id: user.id)
    dates = @foods.map(&:date).sort { |x,y| y <=> x }
    dates.uniq.map {|date| @foods.where(date: date) }
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :foods

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_food, only: [:show, :edit, :update, :destroy]

  def index
    @foods = Food.where(user_id: current_user.id)
    @days = Food.food_history(current_user)
  end

  def new
    @food = Food.new
  end

  def create
    @days = Food.food_history(current_user)
    @food = Food.new(food_params)
    respond_to do |format|
      if @food.save
        format.html {redirect_to foods_path, notice: 'Food Successfuly Added!'}
        format.js
      else
        format.html {render :new, notice: 'There was an error.'}
        format.js { redirect_back(fallback_location: foods_path, notice: 'There was an error.') }
      end
    end
  end

  def edit
  end

  def update
    if @food.update(food_params)
      respond_to do |format|
        if @food.save
          format.html {redirect_to foods_path, notice: 'Food Successfuly Edited!'}
          format.js
        else
          format.html {render :edit, notice: 'There was an error.'}
          format.js { redirect_back(fallback_location: foods_path, notice: 'There was an error.') }
        end
      end
    end
  end

  def destroy
    @food_id = @food.id
    @food_date = @food.date;
    @food.destroy
    respond_to do |format|
      format.html { redirect_to foods_path, notice: 'Your Food has been successfuly deleted.'}
      format.js
    end
  end




private
  def set_food
    @food = Food.find(params[:id])
  end

  def food_params
    params.require(:food).permit(:name, :amount, :calories, :protein, :fat, :carbs, :notes, :date, :user_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!

  def index
    @day = Food.where(user_id: current_user.id).where(date: Time.now)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/foods/_day.html.erb
<% if day.any? %>
  <article class="box post post-excerpt day" id="day-<%= day.first.date.strftime("%b-%d-%Y") %>">
    <header>
      <table class="table">
        <thead class="thead-inverse">
          <tr>
            <th>Name</th>
            <th>Amount</th>
            <th>Calories</th>
            <th>Protein</th>
            <th>Fat</th>
            <th>Carbs</th>
            <th class="edit"></th>
          </tr>
        </thead>
        <tbody id="food-for-<%= day.first.date.strftime("%b-%d-%Y") %>">
          <% day.each do |food| %>
            <%= render 'food_row', food: food %>
          <% end %>
          <tr class="table-active">
            <td>TOTAL</td>
            <td></td>
            <td><%= day.map(&:calories).reduce(0, :+) %></td>
            <td><%= day.map(&:protein).reduce(0, :+) %></td>
            <td><%= day.map(&:fat).reduce(0, :+) %></td>
            <td><%= day.map(&:carbs).reduce(0, :+) %></td>
            <td class="edit"></td>
          </tr>
          <tr class="table-active">
            <% @macro_total = (day.map(&:protein).reduce(0, :+) * 4) + (day.map(&:carbs).reduce(0, :+) * 4) + (day.map(&:fat).reduce(0, :+) * 9) %>
            <td>Macros</td>
            <td></td>
            <td></td>
            <td><%= (4 * day.map(&:protein).reduce(0, :+) / @macro_total * 100).to_i %>%</td>
            <td><%= (9 * day.map(&:fat).reduce(0, :+) / @macro_total * 100).to_i %>%</td>
            <td><%= (4 * day.map(&:carbs).reduce(0, :+) / @macro_total * 100).to_i %>%</td>
            <td class="edit"></td>
          </tr>
        </tbody>
      </table>
    </header>
    <div class="info">
      <span class="date">
        <span class="month"><%= day.first.date.strftime("%b") %></span>
        <span class="day"><%= day.first.date.strftime("%d") %></span>
        <span class="year"><%= day.first.date.strftime("%Y") %></span>
      </span>
      <ul class="stats">
      </ul>
    </div>
  </article>
<% end %>

app/views/foods/_food_row.html.erb
<tr id="food-row-<%= food.id %>">
  <td><%= food.name %></td>
  <td><%= food.amount %></td>
  <td><%= food.calories %></td>
  <td><%= food.protein %></td>
  <td><%= food.fat %></td>
  <td><%= food.carbs %></td>
  <td class="edit"><span id="edit_<%= food.id %>">
    <%= link_to "Edit", edit_food_path(food), {remote: true, 'data-toggle' =>  "modal", 'data-target' => '#modal-window'} %>
  </span> |
  <span id="delete_<%= food.id %>">
    <%= link_to "Delete", food_path(food), remote: true, data: {method: 'delete', :confirm => 'Are You Sure? '} %>
  </span></td>
</tr>

app/views/foods/_form.html.erb
<div class="food-form">
  <%= render "layouts/errors", :object => @food %>

  <%= form_for @food, remote: true do |f| %>
    <div class="row">

      <%= f.hidden_field :user_id, :value => current_user.id %>

      <div class="form-group 4u 12u(small)">
        <%= f.label :name %>
        <%= f.text_field :name %>
      </div>

      <div class="form-group 4u 12u(small)">
        <%= f.label :amount %>
        <%= f.text_field :amount %>
      </div>

      <div class="form-group 4u 12u(small)">
        <%= f.label :calories %>
        <%= f.text_field :calories %>
      </div>

      <div class="form-group 4u 12u(small)">
        <%= f.label :protein %>
        <%= f.text_field :protein %>
      </div>

      <div class="form-group 4u 12u(small)">
        <%= f.label :fat %>
        <%= f.text_field :fat %>
      </div>

      <div class="form-group 4u 12u(small)">
        <%= f.label :carbs %>
        <%= f.text_field :carbs %>
      </div>

      <div class="form-group 4u 12u(small)">
        <%= f.label :notes %>
        <%= f.text_area :notes %>
      </div>


      <div class="form-group 6u 12u(small)">
        <%= f.label :date %>
        <%= f.date_field :date, :value => Time.now.strftime('%Y-%m-%d') %>
      </div>
    </div>
    <%= f.submit %>
  <% end %>
</div>

app/views/foods/_modal.html.erb
<div class="modal-dialog" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <h5 class="modal-title">Modal title</h5>
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true" class="close">&times;</span>
      </button>
    </div>
    <div class="modal-body">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/foods/create.js.erb
$("#modal-shadow").hide();
$("#modal-window").html('');

$('#day-<%= @food.date.strftime("%b-%d-%Y") %>').remove();
$("#all_food").prepend("<%= j render 'day', day: Food.where(user_id: current_user.id).where(date: @food.date) %>")


$(".notice").text("Food Successfuly Added!")
setTimeout(function() {
  $(".notice").text("")
}, 5000);

app/views/foods/destroy.js.erb
$("#modal-shadow").hide();
$("#modal-window").html('');
console.log('#day-<%= @food_date.strftime("%b-%d-%Y") %>')
$('#day-<%= @food_date.strftime("%b-%d-%Y") %>').remove();
if(<%= Food.where(date: @food_date).length %> > 0) {
  $("#all_food").prepend("<%= j render 'day', day: Food.where(user_id: current_user.id).where(date: @food_date) %>");
}


$(".notice").text("Your Food has been successfuly deleted.")
setTimeout(function() {
  $(".notice").text("")
}, 5000);

app/views/foods/edit.js.erb
$("#modal-shadow").show();
$('.food-form').hide();
$("#modal-window").html('<%= j render "modal" %>');

$('.close').on('click', function() {
  $("#modal-shadow").hide();
  $("#modal-window").html('');
});

app/views/foods/index.html.erb
  <%= link_to "Add Food", new_food_path, id: "new_food_link", :class => "btn", remote: true %>


  <hr>

  <div id="all_food">
    <% @days.each do |day| %>
      <%= render 'foods/day', day: day %>
      <hr>
    <% end %>
  </div>

<div id="edit_show"></div>

app/views/foods/new.js.erb
$("#modal-shadow").show();
$('.food-form').hide();
$("#modal-window").html('<%= j render "modal" %>');

$('.close').on('click', function() {
  $("#modal-shadow").hide();
  $("#modal-window").html('');
});

app/views/foods/update.js.erb
$("#modal-shadow").hide();
$("#modal-window").html('');

$('#day-<%= @food.date.strftime("%b-%d-%Y") %>').remove();
$("#all_food").prepend("<%= j render 'day', day: Food.where(user_id: current_user.id).where(date: @food.date) %>");

$(".notice").text("Food Successfuly Edited!")
setTimeout(function() {
  $(".notice").text("")
}, 5000);

app/views/home/_day.html.erb
<article class="box post post-excerpt day">
  <header>
    <table class="table">
      <thead class="thead-inverse">
        <tr>
          <th>Name</th>
          <th>Amount</th>
          <th>Calories</th>
          <th>Protein</th>
          <th>Fat</th>
          <th>Carbs</th>
        </tr>
      </thead>
      <tbody>
        <% day.each do |food| %>
          <tr>
            <td><%= food.name %></td>
            <td><%= food.amount %></td>
            <td><%= food.calories %></td>
            <td><%= food.protein %></td>
            <td><%= food.fat %></td>
            <td><%= food.carbs %></td>
          </tr>
        <% end %>
          <tr class="table-active">
            <td>TOTAL</td>
            <td></td>
            <td><%= day.map(&:calories).reduce(0, :+) %></td>
            <td><%= day.map(&:protein).reduce(0, :+) %></td>
            <td><%= day.map(&:fat).reduce(0, :+) %></td>
            <td><%= day.map(&:carbs).reduce(0, :+) %></td>
          </tr>
          <tr class="table-active">
            <% @macro_total = (day.map(&:protein).reduce(0, :+) * 4) + (day.map(&:carbs).reduce(0, :+) * 4) + (day.map(&:fat).reduce(0, :+) * 9) %>
            <td>Macros</td>
            <td></td>
            <td></td>
            <% if @macro_total > 0 %>
              <td><%= (4 * day.map(&:protein).reduce(0, :+) / @macro_total * 100).to_i %>%</td>
              <td><%= (9 * day.map(&:fat).reduce(0, :+) / @macro_total * 100).to_i %>%</td>
              <td><%= (4 * day.map(&:carbs).reduce(0, :+) / @macro_total * 100).to_i %>%</td>
            <% else %>
              <td></td>
              <td></td>
              <td></td>
            <% end %>
          </tr>
      </tbody>
    </table>
  </header>
  <div class="info">
    <span class="date">
      <span class="month"><%= Time.now.strftime("%b") %></span>
      <span class="day"><%= Time.now.strftime("%d") %></span>
      <span class="year"><%= Time.now.strftime("%Y") %></span>
    </span>
    <ul class="stats">
    </ul>
  </div>
</article>

app/views/home/index.html.erb
<%= render 'home/day', day: @day %>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/_sidebar.html.erb
<!-- Sidebar -->
<div id="sidebar">

	<!-- Logo -->
		<h1 id="logo"><a href="#">STRIPED</a></h1>
    <% if user_signed_in? %>
     Logged in as <strong><%= current_user.email %></strong>
   <% end %>
	<!-- Nav -->
		<nav id="nav">
			<ul>
				<li class="<%= 'current' if current_page?(root_path) %>">
					<%= link_to "Home", root_path %>
				</li>
				<li class="<%= 'current' if current_page?(foods_path) %>">
					<%= link_to "Nutrition", foods_path %>
				</li>
				<!-- <li><a href="#">About Me</a></li>
				<li><a href="#">Contact Me</a></li> -->

        <% if user_signed_in? %>
         <li class="<%= 'current' if current_page?(edit_user_registration_path) %>">
					 <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %>
				 </li>
         <li>
					 <%= link_to "Logout", destroy_user_session_path, :method => "delete", :class => 'navbar-link'%>
				 </li>
       <% else %>
         <li class="<%= 'current' if current_page?(new_user_registration_path) %>">
					 <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'%>
				 </li>
         <li class="<%= 'current' if current_page?(new_user_session_path) %>">
					 <%= link_to "Login", new_user_session_path, :class => 'navbar-link'%>
				 </li>
       <% end %>

			</ul>
		</nav>

	<!-- Calendar -->
		<section class="box calendar">
			<div class="inner">
				<table>
					<caption>July 2014</caption>
					<thead>
						<tr>
							<th scope="col" title="Monday">M</th>
							<th scope="col" title="Tuesday">T</th>
							<th scope="col" title="Wednesday">W</th>
							<th scope="col" title="Thursday">T</th>
							<th scope="col" title="Friday">F</th>
							<th scope="col" title="Saturday">S</th>
							<th scope="col" title="Sunday">S</th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td colspan="4" class="pad"><span>&nbsp;</span></td>
							<td><span>1</span></td>
							<td><span>2</span></td>
							<td><span>3</span></td>
						</tr>
						<tr>
							<td><span>4</span></td>
							<td><span>5</span></td>
							<td><a href="#">6</a></td>
							<td><span>7</span></td>
							<td><span>8</span></td>
							<td><span>9</span></td>
							<td><a href="#">10</a></td>
						</tr>
						<tr>
							<td><span>11</span></td>
							<td><span>12</span></td>
							<td><span>13</span></td>
							<td class="today"><a href="#">14</a></td>
							<td><span>15</span></td>
							<td><span>16</span></td>
							<td><span>17</span></td>
						</tr>
						<tr>
							<td><span>18</span></td>
							<td><span>19</span></td>
							<td><span>20</span></td>
							<td><span>21</span></td>
							<td><span>22</span></td>
							<td><a href="#">23</a></td>
							<td><span>24</span></td>
						</tr>
						<tr>
							<td><a href="#">25</a></td>
							<td><span>26</span></td>
							<td><span>27</span></td>
							<td><span>28</span></td>
							<td class="pad" colspan="3"><span>&nbsp;</span></td>
						</tr>
					</tbody>
				</table>
			</div>
		</section>

	<!-- Copyright -->
		<ul id="copyright">
			<li>&copy; Untitled.</li><li>Design: <a href="http://html5up.net">HTML5 UP</a></li>
		</ul>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HealthTracker</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="/css/striped.css">
    <link rel="stylesheet" href="/css/main.css">
  </head>

  <body>
    <div id="content">
      <div class="inner">
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
        <%= yield %>
      </div>
    </div>
    <%= render 'layouts/sidebar' %>
    <div id="modal-shadow" class="hidden"></div>
    <div id="modal-window" class="alt-modal" role="dialog" aria-labelledby="modal-window"></div>
  </body>
</html>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>